### ISSUE TITLE
Error c2536 under msvc 2013

### ISSUE THREAD

**Issue by povmaniaco** [JerryCao1985/SORT#42]
I find this error with MSVC 2013 under win7 x64. I are fixed on my local repo with this changes:

```cpp
struct Splits
    {
#if defined(_MSC_VER) && _MSC_VER == 1800
        // Fix error c2536 under msvc 2013
        Split*		split[3] = {};      /**< Split planes along three different axis. */
        unsigned	split_c[3] = {};    /**< Number of split planes in each different axis. */
#else
        Split*		split[3] = { nullptr, nullptr, nullptr }; /**< Split planes along three different axis. */
        unsigned	split_c[3] = { 0, 0, 0 };                 /**< Number of split planes in each different axis. */
#endif
        //! Release the allcoated memory.
        void Release()
        {
            SAFE_DELETE_ARRAY(split[0]);
            SAFE_DELETE_ARRAY(split[1]);
            SAFE_DELETE_ARRAY(split[2]);
        }
    };
```

Greetings..

**Comment by JerryCao1985** [comment]
Hi
Thanks for letting me know the issue. 
My take on it is that it is not exactly an issue. Ever since half a year ago, I intended to use C++ features more heavily in my project to shorten the source code. That being said older compilers like VC2008 will not compile my renderer anymore. This compiling error could be caused by the fact that MSVC 2013 doesn't fully support C++ 11. (Although to my knowledge, nullptr and initialization list are supported in it. Kind of surprise to know the error. https://msdn.microsoft.com/en-us/library/hh567368.aspx )

Since I decided to use C++11 more, which means decision has already been made that I will only work on it with latest compilers, I'm afraid that I won't change the code because it is valid code for any decent C++11 compiler to digest.

I agree your code is more compact and elegant. However I just want to avoid the case in which the compiler doesn't set 0 as default value for them.

Thanks anyway.
